### ISSUE TITLE
initarg/initform support for class slots?

### ISSUE THREAD

**Issue by sjl** [eudoxia0/docparser#17]
I'm using docparser to generate some basic API docs.  For class slots, it looks like docparser ignores `initarg` and `initform`, when it might be nice to be able to include them in documentation.  Is there a reason they're not included in the `class-slot-node`s?

**Comment by eudoxia0** [comment]
No reason, this is just a plain old fashioned oversight.

**Comment by eudoxia0** [comment]
I'm gonna work on fixing the build for this before looking deeper into this.

**Comment by eudoxia0** [comment]
Yep this is definitely working now.
