### ISSUE TITLE
The "(define-parser cl:define-condition .." form doesn't set the metaclass slot

### ISSUE THREAD

**Issue by Yehouda** [eudoxia0/docparser#24]
The "(define-parser cl:define-condition .."  form in src/parsers.lisp creates a condition-node object without passing :metaclass. The result is a condition-node with an unbound metaclass slot. That gets an error inside node=, which is done by the class-node method of node=. 

It needs either have a fixed value in the metaclass slot of condition-node, or define-equality for condition-node that ignores the metaclass slot.

**Comment by fisxoj** [comment]
I don't know if it's a correct value, but I ran into this and tried updating the `definet-condition` parser to default `metaclass` to `standard-class`, then I got an error about `default-initargs`.  So, there is more than one problem in this parser.  Would providing `standard-class` and `nil` respectively solve the problem?  I'd be happy to make a PR, but I'm not sure those are the right answers (versus, say, storing the actual class in the `metaclass` slot `(find-class 'standard-class)`)

**Comment by Yehouda** [comment]
**cl:define-condition** processes **:default-initags** the same way as **defclass**, so the value for it in the parser should be the same as the value in the parser for **defclass** in the form that precedes it in the file.

**define-condition** spec:
http://www.lispworks.com/documentation/HyperSpec/Body/m_defi_5.htm

The parser for **defclass** use the symbol in the metaclass, so it should be the symbol.

**cl:define-condition**  doesn't allow **:metaclass**, and the standard says that metaclass of condiitions is not specified (http://www.lispworks.com/documentation/HyperSpec/Body/09_aa.h). 
So it is not obvious what the metaclass should be. Isuggest doing

`(defvar *metaclass-of-condition* (cl:class-name (cl:class-of (cl:find-class 'cl:CONDITION))))`

and use  \*metaclass-of-condition\*.

I am testing it on lispWorks, where it generally doesn't work because it assume it can see macro expansion of top level forms during compilation, which is not true in LispWorks, so I get many failures because of that after doing these fixes.

**Comment by Frechmatz** [comment]
Hi there,

same problem on my side. I've tried the branch provided by @fisxoj and at least for me it fixes the problem.

Example of how to reproduce the error:

docparser-error.asd:

```
(defsystem :docparser-error :components ((:file "conditions")))
```

conditions.lisp:

```
(defpackage :docparser-error (:use :cl))
(in-package :docparser-error)
(define-condition error-1 (error) ())
(define-condition error-2 (error) ())
```

Parse system:

```
olli@Olivers-MBP lisp % sbcl
This is SBCL 2.0.2, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
* (asdf:load-system :docparser)
T
* (docparser:parse :docparser-error)
; compiling file "/Users/olli/src/lisp/docparser-error/conditions.lisp" (written 10 OCT 2020 01:27:15 AM):
; compiling (DEFPACKAGE :DOCPARSER-ERROR ...)
Package: DOCPARSER-ERROR
; compiling (IN-PACKAGE :DOCPARSER-ERROR)
; compiling (DEFINE-CONDITION ERROR-1 ...)
; compiling (DEFINE-CONDITION ERROR-2 ...)
; file: /Users/olli/src/lisp/docparser-error/conditions.lisp
; in: DEFINE-CONDITION ERROR-2
;     (DEFINE-CONDITION DOCPARSER-ERROR::ERROR-2
;         (ERROR)
;         NIL)
; 
; caught ERROR:
;   (during macroexpansion of (DEFINE-CONDITION ERROR-2
;       ...))
;   The slot DOCPARSER::METACLASS is unbound in the object #<condition error-1>.

; compiling (ERROR (QUOTE SB-INT:COMPILED-PROGRAM-ERROR) ...)

; wrote /Users/olli/.cache/common-lisp/sbcl-2.0.2-macosx-x64/Users/olli/src/lisp/docparser-error/conditions-tmpGHU3ALSV.fasl
; compilation finished in 0:00:00.007
; 
; compilation unit aborted
;   caught 1 fatal ERROR condition
;   caught 1 ERROR condition
Compilation error. Ignoring. 
#<DOCPARSER:INDEX {1001FAB9B3}>
* 

```
